name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          cd e-ballot-backend
          export GITHUB_ACTION=True
          python -m pip install --upgrade pip
          pip install ruff pytest
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          cd e-ballot-backend
          python3 -m pytest
