name: PyTests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout GitHub Runner 2
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          cd e-ballot-backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest
        env:
          DB_API_USERNAME: ${{ secrets.admin }}
          DB_API_KEY: ${{ secrets.DB_API_KEY }}
          DB_API_ADDRESS: ${{ secrets.DB_API_ADDRESS }}
          FRONT_END: ${{ secrets.FRONT_END }}
        run:
          cd e-ballot-backend
          python3 -m pytest
